# Site-wide settings
title: Technically, Daria
lang: en
author:
  name: Daria Lutchenko
description: >
  A blog about technical writing: how to make the complex easy and create better docs.
url: "https://techdaria.com"
baseurl: ""
logo: /assets/images/social-preview.png

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-tagging
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

sass:
  quiet_deps: true
  silence_deprecations: [import]

# Minima-specific settings
minima:
  skin: classic
  nav_pages:
    - index.html
    - about.md
  show_excerpts: true
  date_format: "%b %d, %Y"
  social_links:
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/daria-lutchenko/"
    - title: GitHub
      icon: github
      url: "https://github.com/dustgalactic"
  hide_site_feed_link: false

