# Site-wide settings
title: Technically, Daria
description: >
  A blog about technical writing: how to explain complex topics clearly and create better docs for everyone.
url: "https://techdaria.com"
baseurl: ""
permalink: /:title/

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
sass:
  quiet_deps: true
  silence_deprecations: [import]

# Minima-specific settings
minima:
  skin: auto
  nav_pages:
    - index.md
    - about.md
  show_excerpts: true
  date_format: "%b %d, %Y"
  social_links:
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/daria-lutchenko/"
    - title: GitHub
      icon: github
      url: "https://github.com/dustgalactic"
  hide_site_feed_link: false
