# Site-wide settings
title: Technically, Daria
description: >
  A blog about technical writing: how to explain complex topics clearly and create better docs for everyone.
author:
  name: Daria Lutchenko
  email: email@techdaria.com
url: "https://techdaria.com"
baseurl: ""

# Build settings
remote_theme: jekyll/minima@d4d779a
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  quiet_deps: true
  silence_deprecations: [import]

# Minima-specific settings
minima:
  skin: auto
  nav_pages:
    - index.md
    - about.md
  show_excerpts: true
  date_format: "%b %d, %Y"
  social_links:
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/daria-lutchenko/"
    - title: GitHub
      icon: github
      url: "https://github.com/dustgalactic"
  hide_site_feed_link: true
paginate: 5
